#! /bin/bash

# Written by Aheer

printf "\n"
printf "\tNotebook\n\n"
file=$(ls $HOME/custom/Notebook | sort | dmenu -l 10 -fn 'monaco-14' -i)

if [[ $file != 'notebook' && $file != '' ]];
then
	echo -n "Read Or Write: "
	read option

	if [ $option == 'r' ]
	then
		less < $HOME/custom/Notebook/$file
	elif [ $option == 'w' ]
	then
		vim --clean $HOME/custom/Notebook/$file
	else
		echo "Invalid Option!"
	fi
else
	echo filename can\'t be \'notebook\' or empty.
fi
